services:
  ftp:
    hostname: ftpserver
    restart: always
    build:
      context: ..
      dockerfile: ftpserver/Dockerfile
      args:
        - FTP_USER_PASS=${FTP_PASS}
        - UID=${HOST_UID:-1000}
        - GID=${HOST_GID:-1000}
    env_file:
      - ../.env
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftpuser
      FTP_USER_HOME: /home/ftpuser
      # ADDED_FLAGS: "--tls"
    user: "1000:1000"
    volumes:
      - ${PROJECT_ROOT}/data:/home/ftpuser/
      - ${PROJECT_ROOT}/passwd:/etc/pure-ftpd/passwd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
      # healthcheck:
      #   test: ["CMD", "curl", "-f", "http://0.0.0.0:${DJANGO_PORT}/status"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 5
      #   start_period: 40s
